#!/bin/bash

set -e

die () {
    echo "$@" >&2
    exit 1
}

cd "$1"

jq -n \
    --arg description "$(cat description.md)" \
    --arg starter "$(cat starter.py)" \
    --slurpfile meta meta.json \
    --slurpfile io io.json \
    '{
        starter: $starter,
        description: $description,
        meta: $meta[0],
        io: $io[0],
    }' \
    > problem.json || die "Failed to build problem $1"
